//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xkom
{
    using System;
    using System.Collections.Generic;
    
    public partial class koszyk
    {
        public int id { get; set; }
        public int id_zamowienia { get; set; }
        public int id_klienta { get; set; }
        public int status_platnosci { get; set; }
    
        public virtual klient klient { get; set; }
        public virtual zamowienia zamowienia { get; set; }
        public virtual status_platnosci status_platnosci1 { get; set; }
    }
}
