//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xkom
{
    using System;
    using System.Collections.Generic;
    
    public partial class zamowienie_all
    {
        public int Numer_Zamówienia { get; set; }
        public string Nazwa_Produktu { get; set; }
        public Nullable<decimal> Cena_Jednostkowa_Brutto { get; set; }
        public Nullable<double> Cena_Całkowita_Brutto { get; set; }
        public Nullable<double> Cena_Całkowita_Netto { get; set; }
        public Nullable<int> Ilość { get; set; }
    }
}
