//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xkom.DBXkom
{
    using System;
    using System.Collections.Generic;
    
    public partial class cena
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cena()
        {
            this.zamowienia = new HashSet<zamowienia>();
        }
    
        public int id { get; set; }
        public Nullable<int> produkt_id { get; set; }
        public double cena_brutto { get; set; }
        public double stawka_vat { get; set; }
        public double cena_netto { get; set; }
        public double Wartosc_netto { get; set; }
    
        public virtual produkt produkt { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<zamowienia> zamowienia { get; set; }
    }
}
