//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xkom.DBXkom
{
    using System;
    using System.Collections.Generic;
    
    public partial class produkt_all
    {
        public string Nazwa_Produktu { get; set; }
        public string Opis_Produktu { get; set; }
        public string Kategoria { get; set; }
        public string Podkategoria { get; set; }
        public Nullable<decimal> Cena_Brutto { get; set; }
        public Nullable<double> Cena_Netto { get; set; }
        public Nullable<int> Stawka_Vat { get; set; }
    }
}
