//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xkom.DBXkom
{
    using System;
    using System.Collections.Generic;
    
    public partial class status_koszykow
    {
        public string mail { get; set; }
        public string telefon { get; set; }
        public string nazwa_produktu { get; set; }
        public Nullable<double> cena_brutto { get; set; }
        public int ilosc { get; set; }
        public Nullable<double> wartosc { get; set; }
        public string status_platnosci { get; set; }
        public string nazwa_statusu_zamowienia { get; set; }
        public int zamowienie_id { get; set; }
    }
}
