//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xkom.DBXkom
{
    using System;
    using System.Collections.Generic;
    
    public partial class wartosc_zamowienia
    {
        public int Numer_Zamówienia { get; set; }
        public Nullable<double> Koszt_Całkowity_Brutto { get; set; }
        public Nullable<double> Koszt_Całkowity_Netto { get; set; }
        public Nullable<double> Koszt_Całkowity_Stawki_VAT { get; set; }
    }
}
