//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xkom.DBXkom
{
    using System;
    using System.Collections.Generic;
    
    public partial class zamowienia
    {
        public int id { get; set; }
        public int zamowienie_id { get; set; }
        public int produkt_id { get; set; }
        public int cena_id { get; set; }
        public int ilosc { get; set; }
        public int id_klienta { get; set; }
        public int status_platnosci_id { get; set; }
        public int status_zamowienia_id { get; set; }
    
        public virtual cena cena { get; set; }
        public virtual klient klient { get; set; }
        public virtual produkt produkt { get; set; }
        public virtual status_platnosci status_platnosci { get; set; }
        public virtual status_zamowienia status_zamowienia { get; set; }
    }
}
