//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xkom.DBXkom
{
    using System;
    using System.Collections.Generic;
    
    public partial class zamowienia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public zamowienia()
        {
            this.koszyk = new HashSet<koszyk>();
        }
    
        public int id { get; set; }
        public int zamowienie_id { get; set; }
        public int produkt_id { get; set; }
        public int cena_id { get; set; }
        public Nullable<int> ilosc { get; set; }
    
        public virtual cena cena { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<koszyk> koszyk { get; set; }
        public virtual produkt produkt { get; set; }
    }
}
